// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsCQCiksb_9D4e7WH7_WPfcfvnq-1_DoQ',
    appId: '1:606703598389:android:ca0371bc58ff820fd32a7c',
    messagingSenderId: '606703598389',
    projectId: 'outpatientavisena',
    authDomain: 'outpatientavisena.firebaseapp.com',
    storageBucket: 'outpatientavisena.appspot.com',
    measurementId: 'G-F5NH97CPWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCQCiksb_9D4e7WH7_WPfcfvnq-1_DoQ',
    appId: '1:606703598389:android:ca0371bc58ff820fd32a7c',
    messagingSenderId: '606703598389',
    projectId: 'outpatientavisena',
    storageBucket: 'outpatientavisena.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsCQCiksb_9D4e7WH7_WPfcfvnq-1_DoQ',
    appId: '1:606703598389:ios:e9ae5daaa7b9dd6ad32a7c',
    messagingSenderId: '606703598389',
    projectId: 'outpatientavisena',
    storageBucket: 'outpatientavisena.appspot.com',
    iosClientId:
        '606703598389-bhfar0g7oj501tu24rc2f0qqktgujv1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.avisenahealthc',
  );
}
